config/routes.rb
Rails.application.routes.draw do

  resources :bmi_calculators, only: [:index] do
    collection do
      post :calculate
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  def after_sign_in_path_for(resource)
    bmi_calculators_path
  end
end

app/controllers/bmi_calculators_controller.rb
class BmiCalculatorsController < ApplicationController

  def index
  end

  def calculate
    @bmi = BmiCalculator.call(
      unit_system: bmi_params['unit_system'],
      weight: bmi_params['weight'].to_f,
      height: bmi_params['height'].to_f,
    )

    respond_to do |format|
      format.js
    end
  end

  private

  def bmi_params
    params.require(:bmi).permit(:unit_system, :weight, :height)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authenticate_user!

  def index
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bmi_calculators_helper.rb
module BmiCalculatorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bmi_calculators/_results.html.haml
%table.table
  %caption Results
  %thead
    %tr
      %th Body Mass Index
      %th Body Mass Index Category
  %tbody
    %tr
      %td= @bmi.bmi_value
      %td= @bmi.bmi_category

app/views/bmi_calculators/calculate.js.erb
$('#bmi_result').html("<%= escape_javascript(render partial: 'results', locals: { bmi: @bmi })%>");

app/views/bmi_calculators/index.html.haml
= content_for :javascript_onbody do
  = javascript_include_tag('bmi_calculator.js')

.row
  .col-md-offset-3.col-md-6
    = form_for(:bmi, url: calculate_bmi_calculators_path, remote: true) do |f|
      .form-group
        = f.select(:unit_system, { 'Metric system' => 'm', 'English system' => 'e' }, {}, {class: 'form-control'})
      .form-group
        = f.label :weight
        = f.number_field :weight
        %span#weight_unit
          kg
      .form-group
        = f.label :height
        = f.number_field :height, step: :any
        %span#height_unit
          m
      .form-group
        = f.submit 'Calculate BMI', class: 'btn btn-default'

.row
  #bmi_result.col-md-offset-3.col-md-6

app/views/home/index.html.haml
.jumbotron
  %h1 BMI Calculator
  %p
    Welcome to the Body Mass Index calculator, here you can get to know your BMI category so you can learn
    just how healthy or unhealthy your current weight is accordingly to international health standars.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Body Mass Index calculator
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tag

  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %a.navbar-brand{href: current_user ? bmi_calculators_path : root_path} BMI Calculator
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li
                = link_to 'Sign out', destroy_user_session_path, data:  { method: :delete }
            - else
              %li
                = link_to 'Log in', new_user_session_path
              %li
                = link_to 'Register', new_user_registration_path

    .container{role: 'main'}
      = yield

      = content_for :javascript_onbody